# Generated by Django 5.2.5 on 2025-08-30 05:33

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=users.models.user_photo_path),
        ),
    ]
